name: 01_Lint_and_Test

on:
  push:
    paths:
      - "**/*.go"
      - "go.mod"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    env:
      TSITANYA_WORKSPACE: kube-itog-tsitanya
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2

      - name: Test
        run: go test ./...
